# Generated by Django 3.0.5 on 2020-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
                ('Time', models.TimeField(auto_now=True)),
                ('Notes', models.TextField()),
                ('Contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Web users contacts',
                'db_table': 'User_Contact',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Subsidiaries  Section'},
        ),
        migrations.AddField(
            model_name='about',
            name='Facebook',
            field=models.CharField(blank=True, max_length=145),
        ),
        migrations.AddField(
            model_name='about',
            name='Instagram',
            field=models.CharField(blank=True, max_length=145),
        ),
        migrations.AddField(
            model_name='about',
            name='Twitter',
            field=models.CharField(blank=True, max_length=145),
        ),
    ]
