# Generated by Django 2.2 on 2020-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_footer_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='Phone',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
