# Generated by Django 2.2 on 2020-04-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_footer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
