# Generated by Django 2.2 on 2020-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Image',
        ),
    ]
