# Generated by Django 2.2 on 2020-04-16 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home'),
            preserve_default=False,
        ),
    ]
