# Generated by Django 2.2 on 2020-04-16 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
