# Generated by Django 2.2 on 2020-04-16 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_projects_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiaries',
            name='Url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
